### ISSUE TITLE
im ur dad

### ISSUE THREAD

**Issue by Clxser** [cqdetdev/draco#1]
lYeah, Pluto
You better not raise your voice at me
You know I got a pimp degree
Yeah, Pluto
Draco season with the bookbag
Rat-tat got a little kickback
Hundreds on hundreds got a good batch
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
Lamborghini doors, but I never stop
Fuck around got a nigga pissed off
Nice little thot got stiff arm
Did the Heisman on the hoe got the stiff arm
Fuck up that body like Tyson or Holyfield
Whoa, whoa, whoa, whoa, whoa, whoa (you know)
A couple of pills and I got my soda filled
Whoa, whoa, whoa, whoa, whoa, whoa (you know)
Break out a sweat, I go head over heels for these meals
Whoa, whoa, whoa, whoa, whoa (you know)
She thinks she the one, but to me she ain't nothing but a thrill
Whoa, whoa, whoa, whoa, whoa (you know)
I've been drippin' like a god, what else?
I been dodgin' all the flage, what else?
I been fillin' up garages, what else?
I gave her her first ménage, what else?
Uh, close your eyes, eyes, eyes
I'm about to slide, slide, slide
Wonder why, why, why
I stay in the sky, sky, sky
Pink Molly, let me dance with her
Freestylin', let me dance with her
Sky Dweller, it was sentimental
Rose gold, it was cinnamon
Draco season with the bookbag
Rat-tat, got a little kick back
Hundreds on hundreds got a good batch
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
Fuck up my bitch by the change
Want me to jump out the stage (jump out the stage)
I wanna jump in the air
You know the love ain't fair
You killin' then show us the proof
I already got the juice
Chain different colors like fruits
I like to hang out the roof
I got to train my bitches
I'm putting chains on my bitches (I'm putting chains on 'em)
I'll pull some chain on the snitches (I'll pull some chain on the snitches)
I'm focused I'm back on my mission (yeah)
Flex on a nigga, no apologies (flex on 'em)
Molly off-white, done got to me (Flex on 'em)
Playing hockey with the ice in the Major League (yeah)
35 bitches at the St. Reg (yeah)
Fall back shooter like KD
Back in the kitchen with the curry (curry)
Pullin' up with Xan', can't hurt me (hurt me)
Pineapple drink lookin' syrupy (syrupy)
56 nights, I was dirty (56)
Styrofoam cups servin' patients (woo)
Heard you been talkin' 'bout the kid (kid)
Knowin' damn well that's a flagrant (technical)
I cancel two bitches (cancel 'em)
I got me some new bitches (got 'em, got 'em)
Come check out how I'm living (check out how I'm living)
I got me some new jewelry (I got me some new jewelry)
I got me some new drip (got me some new drip)
Ain't got nothing to do with it (ain't got nothing to do with it)
I'll give my bitch to you (I'll give my bitch to you)
If that what she mean to you (if that what she mean)
Draco season with the bookbag
Rat-tat got a little kickback
Hundreds on hundreds got a good batch
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
Draco season with the bookbag
Rat-tat got a little kickback
Hundreds on hundreds got a good batch
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
You ain't never ever get you bitch back
Yacht cruisin' in the deep
I'm twisted up I got geeked
Misbehaving with your freak
Can't tell she got teeth
I was in her mouth like veneers
Start comparing my career
Designer flooded through the crib
Business furniture for real
I bought a Fendi couch for my kids
They just want to plug a nigga wig
Charge a half a mil' for the gig
Middle fingers up fuck the pigs
Diamonds fallin' off my let me jig
Never falling off and never quit
I retired cookin' up a brick
Certified nigga out the 6
Who was rapping diamonds in the zone
I was chargin' 10 for the strong
Keep on goin' in on this song
Keep an F&N at your home
Lesson learned and we moving on
I got firm niggas, Al Capone
Got my Chi niggas on the horn
Downtown Atlanta I was born

**Comment by cqdetdev** [comment]
why
