### ISSUE TITLE
Insane multiversion

### ISSUE THREAD

**Issue by Superomarking** [cqdetdev/draco#3]
`2022/09/10 15:16:22 error: BallinGoat connected with an incompatible protocol: expected protocol = 545, client protocol = 544`

**Comment by didntpot** [comment]
Clone the repo and update gophertunnel? @Superomarking

**Comment by Superomarking** [comment]
> Clone the repo and update gophertunnel? @Superomarking

peppa comes with the clutch frffrfrfrfrrrrrr
