### ISSUE TITLE
Help WTF

### ISSUE THREAD

**Issue by xKaOz** [cqdetdev/draco#7]
Dude what the fuck 😭

I was scrolling through GitHub and I come across this very good (*shit) repository.

At first I was a little sceptical about downloading this, but then I decided to take the risk. 

So I downloaded it and followed the steps, when I got to step 2 and ran the command you said (CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe") my computer literally blown up, and my house burned down and killed 3 people and now I am permanently blind, thanks.

**Comment by cqdetdev** [comment]
its cause u like men
